// Generated by CoffeeScript 1.6.1
(function() {
  var EvaluateFromStream, TwitterAccess, stream;

  EvaluateFromStream = require("./lib/EvaluateFromStream");

  TwitterAccess = require('./lib/TwitterAccess');

  stream = new EvaluateFromStream("http://localhost:5000", TwitterAccess.init());

  stream.start();

}).call(this);
