// Generated by CoffeeScript 1.6.1
(function() {
  var twit, twitter, util;

  util = require('util');

  twitter = require('twitter');

  twit = new twitter({
    consumer_key: 'mCp0qZ0zGGcvA9ZKVo7xQ',
    consumer_secret: 'X1Z4FaK8Hv68ZoTUCmiRjDy6IP5d5n7OHYwC6es4A',
    access_token_key: '11510772-MZIWUADlvY7A9Cbz6kKpqbuRM7EfWrdskAnXNpxpE',
    access_token_secret: process.argv[2]
  });

  twit.stream('statuses/sample', function(stream) {
    return stream.on('data', function(data) {
      return console.log(util.inspect(data));
    });
  });

}).call(this);
