// Generated by CoffeeScript 1.6.1
(function() {
  var LatLon, Stream, TweetCountsFactory, TweetTokenizer, app, express, geohash, port, stream, tweetCounts, twit, twitter, _;

  express = require("express");

  app = express();

  app.use(express.logger());

  twitter = require('twitter');

  _ = require('underscore');

  geohash = require('ngeohash');

  LatLon = require("./lib/LatLon");

  TweetCountsFactory = require("./lib/TweetCountsFactory");

  TweetTokenizer = require("./lib/TweetTokenizer");

  Stream = require("./lib/Stream");

  twit = new twitter({
    consumer_key: 'mCp0qZ0zGGcvA9ZKVo7xQ',
    consumer_secret: 'X1Z4FaK8Hv68ZoTUCmiRjDy6IP5d5n7OHYwC6es4A',
    access_token_key: '11510772-MZIWUADlvY7A9Cbz6kKpqbuRM7EfWrdskAnXNpxpE',
    access_token_secret: process.env['TWITTER_ACCESS_TOKEN_SECRET']
  });

  tweetCounts = TweetCountsFactory.create(2);

  stream = new Stream(tweetCounts, twit, new TweetTokenizer(2));

  stream.start();

  app.all('*', function(req, resp, next) {
    resp.header("Access-Control-Allow-Origin", "*");
    resp.header("Access-Control-Allow-Headers", "X-Requested-With");
    return next();
  });

  app.get('/', function(req, resp) {
    return resp.send('Hello World!');
  });

  app.get('/counts.json', function(req, resp) {
    return tweetCounts.dump(function(dumped) {
      return resp.send(dumped);
    });
  });

  app.get('/counts/grouped-by-geohash/precision-:precision.json', function(req, resp) {
    return tweetCounts.dump(function(dumped) {
      var byGeoHash, counts;
      byGeoHash = _.countBy(dumped.counts, function(entry) {
        return geohash.encode(entry.lat_lon.latitude, entry.lat_lon.longitude, req.params.precision);
      });
      counts = _.map(byGeoHash, function(count, encoded) {
        return {
          'lat_lon': geohash.decode(encoded),
          'count': count
        };
      });
      return resp.send({
        'total': dumped.total,
        'counts': counts
      });
    });
  });

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
