// Generated by CoffeeScript 1.6.1
(function() {
  var GeoHashRegion, LatLon, geohash;

  geohash = require('ngeohash');

  LatLon = require('./LatLon');

  GeoHashRegion = (function() {

    function GeoHashRegion(center, error, hash) {
      this.center = center;
      this.error = error;
      this.hash = hash;
    }

    GeoHashRegion.prototype.toHash = function(precision) {
      return geohash.encode(this.center.latitude, this.center.longitude, precision);
    };

    GeoHashRegion.prototype.boundingBox = function() {
      return {
        topLeft: new LatLon(this.center.latitude + this.error.latitude, this.center.longitude - this.error.longitude),
        bottomRight: new LatLon(this.center.latitude - this.error.latitude, this.center.longitude + this.error.longitude)
      };
    };

    GeoHashRegion.fromPointInRegion = function(latLon, precision) {
      var hash;
      hash = geohash.encode(latLon.latitude, latLon.longitude, precision);
      return GeoHashRegion.fromHash(hash);
    };

    GeoHashRegion.fromHash = function(hash) {
      var center, decoded;
      decoded = geohash.decode(hash);
      center = new LatLon(decoded.latitude, decoded.longitude);
      return new GeoHashRegion(center, decoded.error, hash);
    };

    return GeoHashRegion;

  })();

  module.exports = GeoHashRegion;

}).call(this);
