// Generated by CoffeeScript 1.6.1
(function() {
  var GeoHashRegion, LatLon, geohash;

  geohash = require('ngeohash');

  LatLon = require('./LatLon');

  GeoHashRegion = (function() {

    function GeoHashRegion(center, hash) {
      this.center = center;
      this.hash = hash;
    }

    GeoHashRegion.prototype.toHash = function(precision) {
      return geohash.encode(this.center.latitude, this.center.longitude, precision);
    };

    GeoHashRegion.fromPointInRegion = function(latLon, precision) {
      var hash;
      hash = geohash.encode(latLon.latitude, latLon.longitude, precision);
      return GeoHashRegion.fromHash(hash);
    };

    GeoHashRegion.fromHash = function(hash) {
      var center, decoded;
      decoded = geohash.decode(hash);
      center = new LatLon(decoded.latitude, decoded.longitude);
      return new GeoHashRegion(center, hash);
    };

    return GeoHashRegion;

  })();

  module.exports = GeoHashRegion;

}).call(this);
