// Generated by CoffeeScript 1.6.1
(function() {
  var Graphite, NoOpGraphite, dgram,
    _this = this;

  dgram = require('dgram');

  NoOpGraphite = (function() {

    function NoOpGraphite() {}

    NoOpGraphite.prototype.send = function(name, value) {};

    return NoOpGraphite;

  })();

  Graphite = (function() {

    function Graphite(apikey) {
      var _this = this;
      this.apikey = apikey;
      this.send = function(name, value) {
        return Graphite.prototype.send.apply(_this, arguments);
      };
      this.client = dgram.createSocket("udp4");
    }

    Graphite.prototype.send = function(name, value) {
      var message;
      message = new Buffer(this.apikey + ("." + name + " " + value + "\n"));
      return this.client.send(message, 0, message.length, 2003, "carbon.hostedgraphite.com", function(err, bytes) {
        return this.client.close();
      });
    };

    Graphite.initializeInHeroku = function() {
      var apikey;
      apikey = process.env.HOSTEDGRAPHITE_APIKEY;
      if (apikey != null) {
        return new Graphite(apikey);
      } else {
        return new NoOpGraphite();
      }
    };

    return Graphite;

  })();

  module.exports = Graphite;

}).call(this);
