// Generated by CoffeeScript 1.6.1
(function() {
  var LatLon, geohash;

  geohash = require('ngeohash');

  LatLon = (function() {

    function LatLon(lat, lon) {
      this.latitude = lat;
      this.longitude = lon;
    }

    LatLon.prototype.toId = function() {
      return "" + this.latitude + "," + this.longitude;
    };

    LatLon.prototype.toGeoHash = function(precision) {
      return geohash.encode(this.latitude, this.longitude, precision);
    };

    LatLon.fromId = function(id) {
      var latS, lonS, _ref;
      _ref = id.split(","), latS = _ref[0], lonS = _ref[1];
      return new LatLon(parseFloat(latS), parseFloat(lonS));
    };

    LatLon.fromGeoHash = function(geoHash) {
      var decoded;
      decoded = geohash.decode(geoHash);
      return new LatLon(decoded.latitude, decoded.longitude);
    };

    return LatLon;

  })();

  module.exports = LatLon;

}).call(this);
