// Generated by CoffeeScript 1.6.1
(function() {
  var ByMostTweets, BySumOfTFIDFScore, NearestRegionFinder, _;

  _ = require('underscore');

  ByMostTweets = require("./finders/ByMostTweets");

  BySumOfTFIDFScore = require("./finders/BySumOfTFIDFScore");

  NearestRegionFinder = (function() {

    function NearestRegionFinder(tweetCounts) {
      this.tweetCounts = tweetCounts;
      this.finders = [
        {
          name: 'by_most_tweets',
          finder: new ByMostTweets(this.tweetCounts)
        }, {
          name: 'by_sum_of_tfidf_score',
          finder: new BySumOfTFIDFScore(this.tweetCounts)
        }
      ];
    }

    NearestRegionFinder.prototype.nearest = function(signature, limit, callback) {
      var entry, found, nearest, _i, _len, _ref, _results,
        _this = this;
      nearest = {};
      found = 0;
      _ref = this.finders;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entry = _ref[_i];
        _results.push((function(entry) {
          return entry.finder.nearest(signature, limit, function(results) {
            found += 1;
            nearest[entry.name] = results;
            if (found === _this.finders.length) {
              return callback(nearest);
            }
          });
        })(entry));
      }
      return _results;
    };

    return NearestRegionFinder;

  })();

  module.exports = NearestRegionFinder;

}).call(this);
