// Generated by CoffeeScript 1.6.1
(function() {
  var NearestRegionFinder, _;

  _ = require('underscore');

  NearestRegionFinder = (function() {

    function NearestRegionFinder(tweetCounts) {
      this.tweetCounts = tweetCounts;
    }

    NearestRegionFinder.prototype.nearest = function(signature, limit, callback) {
      var _this = this;
      return this.tweetCounts.tweetCountsPerRegion(function(results) {
        return callback({
          'by_most_tweets': _.chain(results).sortBy(function(d) {
            return -1 * d.tweets;
          }).first(limit).pluck("region").filter(function(d) {
            return d.hash !== "[object Object]";
          }).value()
        });
      });
    };

    return NearestRegionFinder;

  })();

  module.exports = NearestRegionFinder;

}).call(this);
