// Generated by CoffeeScript 1.6.1
(function() {
  var RegionFromPhraseSignature;

  RegionFromPhraseSignature = (function() {

    function RegionFromPhraseSignature() {}

    return RegionFromPhraseSignature;

  })();

  module.exports = RegionFromPhraseSignature;

}).call(this);
