// Generated by CoffeeScript 1.6.3
(function() {
  var Snapshotter, URL,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  URL = require("url");

  Snapshotter = (function() {
    function Snapshotter(s3) {
      this.s3 = s3;
      this._snapshot = __bind(this._snapshot, this);
      this.beginPolling = __bind(this.beginPolling, this);
    }

    Snapshotter.prototype.beginPolling = function(url, path, interval) {
      var _this = this;
      console.log("Will collect snapshot of " + url + " every " + interval + " millis");
      return setInterval(function() {
        return _this._snapshot(url, path);
      }, interval);
    };

    Snapshotter.prototype._snapshot = function(URL, destination) {
      var timestamp;
      timestamp = Date.now();
      return console.log("Snapshotting at " + timestamp);
    };

    return Snapshotter;

  })();

  module.exports = Snapshotter;

}).call(this);

/*
//@ sourceMappingURL=Snapshotter.map
*/
