// Generated by CoffeeScript 1.6.1
(function() {
  var Stream,
    _this = this;

  Stream = (function() {

    function Stream(twitter, restartAfterSeconds) {
      var _this = this;
      this.twitter = twitter;
      if (restartAfterSeconds == null) {
        restartAfterSeconds = 30 * 60;
      }
      this.restart = function() {
        return Stream.prototype.restart.apply(_this, arguments);
      };
      this.restartAfterMillis = restartAfterSeconds * 1000;
    }

    Stream.prototype.start = function() {
      var _this = this;
      return this.twitter.stream('statuses/sample', function(stream) {
        _this.stream = stream;
        console.log("Started listening for tweets, will restart after " + _this.restartAfterMillis + " millis");
        stream.on('data', _this.handleData);
        return setTimeout(_this.restart, _this.restartAfterMillis);
      });
    };

    Stream.prototype.restart = function() {
      if (this.stream != null) {
        console.log("Destroying stream");
        this.stream.destroy();
      }
      return this.start();
    };

    return Stream;

  })();

  module.exports = Stream;

}).call(this);
