// Generated by CoffeeScript 1.6.1
(function() {
  var SurprisingNGrams, _;

  _ = require('underscore');

  SurprisingNGrams = (function() {

    function SurprisingNGrams(tweetCounts) {
      this.tweetCounts = tweetCounts;
    }

    SurprisingNGrams.prototype.surprisingNGramsForRegion = function(region, callback) {
      var _this = this;
      return this.tweetCounts.overallNGramCounts(function(overall) {
        return _this.tweetCounts.ngramCountsForRegion(region, function(forRegion) {
          var forRegionMap, forRegionSum, overallMap, overallSum, result, surpriseFn;
          overallSum = _this.sumNGrams(overall);
          overallMap = _this.toMap(overall);
          forRegionSum = _this.sumNGrams(forRegion);
          forRegionMap = _this.toMap(forRegion);
          surpriseFn = function(d) {
            var forRegionRatio, overallRatio, surprise;
            overallRatio = overallMap[d.ngram] / overallSum;
            forRegionRatio = forRegionMap[d.ngram] / forRegionSum;
            surprise = forRegionRatio / overallRatio;
            return {
              ngram: d.ngram,
              tweets: d.tweets,
              expectedRatio: overallRatio,
              actualRatio: forRegionRatio,
              surprise: surprise
            };
          };
          result = _.chain(forRegion).map(surpriseFn).sortBy(function(d) {
            return -1 * d.surprise;
          }).value();
          return callback(result);
        });
      });
    };

    SurprisingNGrams.prototype.sumNGrams = function(d) {
      return _.chain(d).pluck("tweets").reduce((function(m, d) {
        return m + d;
      }), 0).value();
    };

    SurprisingNGrams.prototype.toMap = function(d) {
      return _.chain(d).reduce((function(m, d) {
        m[d.ngram] = d.tweets;
        return m;
      }), {}).value();
    };

    return SurprisingNGrams;

  })();

  module.exports = SurprisingNGrams;

}).call(this);
