// Generated by CoffeeScript 1.6.1
(function() {
  var NGrams, TweetTokenizer, _,
    _this = this;

  _ = require('underscore');

  NGrams = require("natural").NGrams;

  TweetTokenizer = (function() {

    function TweetTokenizer(length) {
      var _this = this;
      this.length = length;
      this.nGrams = function(text) {
        return TweetTokenizer.prototype.nGrams.apply(_this, arguments);
      };
    }

    TweetTokenizer.prototype.nGrams = function(text) {
      var nGrams, nGramsForEachWord, word, words;
      if (text.length === 0) {
        return {
          'length': this.length,
          'nGrams': []
        };
      } else {
        words = text.toLowerCase().split(/\s+/);
        nGramsForEachWord = _.flatten((function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = words.length; _i < _len; _i++) {
            word = words[_i];
            _results.push(NGrams.ngrams(word.split(""), this.length));
          }
          return _results;
        }).call(this), true);
        nGrams = _.uniq(_.map(nGramsForEachWord, function(d) {
          return d.join("");
        }));
        return {
          'length': this.length,
          'nGrams': nGrams
        };
      }
    };

    return TweetTokenizer;

  })();

  module.exports = TweetTokenizer;

}).call(this);
