// Generated by CoffeeScript 1.6.1
(function() {
  var RedisTweetCounts, TweetCountsFactory, redis, url;

  redis = require('redis');

  url = require('url');

  RedisTweetCounts = require('./RedisTweetCounts');

  TweetCountsFactory = (function() {

    function TweetCountsFactory() {}

    TweetCountsFactory.create = function() {
      var client, redisURL;
      if (process.env.REDISCLOUD_URL != null) {
        console.log("Using RedisCloud Redis");
        redisURL = url.parse(process.env.REDISCLOUD_URL);
        client = redis.createClient(redisURL.port, redisURL.hostname, {
          no_ready_check: true
        });
        client.auth(redisURL.auth.split(":")[1]);
      } else {
        console.log("Using Local Redis");
        client = redis.createClient();
      }
      return new RedisTweetCounts(client);
    };

    return TweetCountsFactory;

  })();

  module.exports = TweetCountsFactory;

}).call(this);
