// Generated by CoffeeScript 1.6.1
(function() {
  var LatLon, Stream, TweetCountsFromStream,
    _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LatLon = require("./LatLon");

  Stream = require("./Stream");

  TweetCountsFromStream = (function(_super) {

    __extends(TweetCountsFromStream, _super);

    function TweetCountsFromStream(tweetCounts, twitter, tokenizer, restartAfterSeconds) {
      var _this = this;
      this.tweetCounts = tweetCounts;
      this.tokenizer = tokenizer;
      this.handleData = function(data) {
        return TweetCountsFromStream.prototype.handleData.apply(_this, arguments);
      };
      TweetCountsFromStream.__super__.constructor.call(this, twitter, restartAfterSeconds);
    }

    TweetCountsFromStream.prototype.handleData = function(data) {
      if ((data.geo != null) && (data.geo.coordinates != null)) {
        return this.tweetCounts.add(new LatLon(data.geo.coordinates[0], data.geo.coordinates[1]), this.tokenizer.nGrams(data.text));
      }
    };

    return TweetCountsFromStream;

  })(Stream);

  module.exports = TweetCountsFromStream;

}).call(this);
