// Generated by CoffeeScript 1.6.1
(function() {
  var ByMostTweets, _;

  _ = require('underscore');

  ByMostTweets = (function() {

    function ByMostTweets(tweetCounts) {
      this.tweetCounts = tweetCounts;
    }

    ByMostTweets.prototype.nearest = function(signature, limit, callback) {
      var _this = this;
      return this.tweetCounts.tweetCountsPerRegion(function(results) {
        return callback(_.chain(results).sortBy(function(d) {
          return -1 * d.tweets;
        }).first(limit).pluck("region").filter(function(d) {
          return d.hash !== "[object Object]";
        }).value());
      });
    };

    return ByMostTweets;

  })();

  module.exports = ByMostTweets;

}).call(this);
