// Generated by CoffeeScript 1.6.1
(function() {
  var GeoHashRegion, LatLon, assert, vows;

  vows = require('vows');

  assert = require('assert');

  GeoHashRegion = require('../../lib/GeoHashRegion');

  LatLon = require('../../lib/LatLon');

  vows.describe('GeoHash').addBatch({
    'when given lat/lon point': {
      topic: new LatLon(57.64911, 10.40744),
      'can find covering geohash region with desired precision': function(latLon) {
        var region;
        region = GeoHashRegion.fromPointInRegion(latLon, 11);
        assert.equal(11, region.hash.length);
        return assert.equal("u4pruydqqvj", region.hash);
      },
      'reducing precision gives geohash region which is prefix of higher precision geohash region': function(latLon) {
        var region;
        region = GeoHashRegion.fromPointInRegion(latLon, 5);
        return assert.equal("u4pru", region.hash);
      }
    },
    'when given geohash': {
      topic: "u4pruydqqvj",
      'can round-trip back to lat/lon center': function(geoHash) {
        var region;
        region = GeoHashRegion.fromHash(geoHash);
        assert.equal(57.64911, region.center.latitude.toFixed(5));
        return assert.equal(10.40744, region.center.longitude.toFixed(5));
      }
    }
  })["export"](module);

}).call(this);
